{"name": "test_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test_allure.TestCase object at 0x000001FE6CB09A90>\n\n    def test_03(self):\n        print('---用例03---')\n>       assert 0\nE       assert 0\n\ntest_allure.py:17: AssertionError"}, "attachments": [{"name": "stdout", "source": "7b6a6655-1030-4ba8-986b-c42ab5e59ef3-attachment.txt", "type": "text/plain"}], "start": 1661160163979, "stop": 1661160163979, "uuid": "a3ae132b-109d-4c6c-999d-568452c53151", "historyId": "5aa853a65b61761388714ee4e7c30e75", "testCaseId": "fa3c4fdde70382a5a009cf1645c194b5", "fullName": "test_allure.TestCase#test_03", "labels": [{"name": "suite", "value": "test_allure"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "PS2021TPEHOVIZ"}, {"name": "thread", "value": "27496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}